import glob
import os
import chess
import chess.pgn
import chess.svg
import chess.engine

import cairosvg
from discord_webhook import DiscordWebhook, DiscordEmbed
from io import BytesIO

# function to get the path of the most recently modified PGN file
def get_last_modified(path):
    list_of_files = sorted(glob.glob(path + '/*.pgn'))
    return 'games/current.pgn' if 'games/current.pgn' in list_of_files else list_of_files[-1]

# function to load the current board state from a PGN file
def load_board(file):
    with open(file) as pgn_file:
        game = chess.pgn.read_game(pgn_file)
        board = game.board()

    # replay the game moves to get the current board state
    for move in game.mainline_moves():
        board.push(move)

    return board

# function to generate a PNG image from an SVG string
def generate_png(svg):
    out = BytesIO()
    cairosvg.svg2png(bytestring=svg, write_to=out)
    out.seek(0)

    return out

# function to convert a chess move to Standard Algebraic Notation (SAN)
def move_to_san(board, move):
    if move is None:
        return "None"

    return str(board.fullmove_number) + ('... ' if board.turn == chess.BLACK else '. ') + board.san(move)

# function to get the evaluation of the current board state from the Stockfish engine
def get_evaluation(board, time_limit):
    stockfish_path = os.environ['STOCKFISH_PATH']
    engine = chess.engine.SimpleEngine.popen_uci(stockfish_path)

    # analyze the position and get the evaluation and recommended next move
    info = engine.analyse(board, chess.engine.Limit(time=time_limit))
    engine.quit()

    score = info['score'].white()
    next_move = move_to_san(board, info['pv'][0] if 'pv' in info else None)
    mate = score.mate()
    score = score.score()

    if mate is not None:
        # if the evaluation is a mate, format it as '#<number of moves>'
        return '#{:+d}'.format(mate), next_move
    else:
        # if the evaluation is not a mate, format it as '+/-<score>'
        return '{:+.2f}'.format(score / 100), next_move

# function to send a Discord webhook with the current board state and evaluation
def send_webhook(png, last_move, pts, move, board):
    webhook_url = os.environ['WEBHOOK_URL']
    webhook = DiscordWebhook(url=webhook_url, username='README Chess', avatar_url='https://github.com/ChessCom.png')
    webhook.add_file(file=png.read(), filename='image.png')

    # create an embed for the webhook with the current evaluation and recommended next move
    embed = DiscordEmbed(title=last_move, description='New move played', color=(0xefefef if board.turn == chess.WHITE else 0x303030))
    embed.set_footer(text='Generated by marcizhu/readme-chess')
    embed.set_timestamp()
    embed.add_embed_field(name='Evaluation', value=pts)
    embed.add_embed_field(name='Next best move', value=move)
    embed.set_image(url='attachment://image.png')

    # add the embed to the webhook and send it
    webhook.add_embed(embed)
    webhook.execute()

# function to define the light blue board style
def style_lightblue():
    colors = dict()
    colors['square
